server:
  port: 8080

spring:
  application:
    name: IELTS-ZONE-REGISTRY-SERVICE
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/ielts_zone
#    username: postgres
#    password: 1212
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost

