server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ielts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: IELTS-ZONE-FILE-SERVICE
  jackson:
    serialization:
      fail-on-empty-beans: false
  cloud:
    loadbalancer:
      ribbon:
        eureka:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

file:
  upload-dir: C:\Abdurahmon\Photo & Videos\Bot

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha