server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ielts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: IELTS-ZONE-FILE-SERVICE
  jackson:
    serialization:
      fail-on-empty-beans: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

file:
  upload-dir: IeltsZoneFileService\src\main\resources\files