server:
  port: 8085

spring:
  application:
    name: IELTS-ZONE-USER-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ielts
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  cloud:
    loadbalancer:
      ribbon:
        eureka:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost