spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/write_questions_bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: WriteQuestionsBot

server:
  port: 8090

logging:
  level:
    org:
      hibernate: INFO
      springframework: INFO