spring:
  application:
    name: WRITE-QUESTIONS-BOT
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ielts_zone
    username: postgres
    password: 1212
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8086