spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/write_questions_bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: WriteQuestionsBot

server:
  port: 8090