package uz.ieltszone.writequestionsbot.service.bot.enums;

public enum Operation {
    LOGIN_PHONE_NUMBER,

    // for application

    ASK_FOR_TASK,
    ASK_FOR_QUESTION,
    ASK_FOR_LEARNING_CENTER,
    ASK_FOR_ANSWER,
    ASK_FOR_WHEN_TIME,
    ASK_FOR_PHOTO_EXIST,
    ASK_FOR_PHOTO,
    ASK_FOR_QUESTION_FOR_SECOND,
    ASK_FOR_PHOTO_EXIST_FOR_SECOND,
    ASK_FOR_PHOTO_FOR_SECOND, ASK_FOR_QUESTION_TASK_1, ASK_FOR_PHOTO_TASK_1, ASK_FOR_QUESTION_FOR_TASK_1, ASK_FOR_TASK_1_EXISTS, ASK_FOR_TASK_2_QUESTION_FROM_TASK_1, ASK_FOR_PHOTO_TASK_1_BEFORE_TASK_2, ASK_FOR_TASK_2_QUESTION_FROM_TASK_1_PHOTO,
}